### ISSUE TITLE
vm2 dependency still there

### ISSUE THREAD

**Issue by ir-fuel** [jonkemp/inline-css#128]
You have updated the code so `remote-content` no longer uses the `superagent` dependency which pulled in a vulnerable `vm2` dependency.

However you did not update any version numbers, not on `inline-css` and not on `remote-content`, so people who don't wipe `node-modules` before running `npm install` will not get updated versions for this.

this is what `npm ls contextify vm2` shows right now on my computer:
```
└─┬ inline-css@4.0.2
  └─┬ extract-css@3.0.1
    └─┬ href-content@2.0.2
      └─┬ remote-content@3.0.1
        └─┬ superagent-proxy@3.0.0
          └─┬ proxy-agent@5.0.0
            └─┬ pac-proxy-agent@5.0.0
              └─┬ pac-resolver@5.0.1
                └─┬ degenerator@3.0.4
                  └── vm2@3.9.19
```

**Comment by ir-fuel** [comment]
It's even worse it seems. I deleted `package-lock.json`, `node_modules` and I force cleaned the npm cache, and I still get the above dependency tree imported in the project

**Comment by jonkemp** [comment]
Thanks. I am aware. This is a monorepo so it's more complicated and I'm looking into converting it to use Turborepo. I just haven't gotten to it yet. Sorry for the delay.

**Comment by LucVidal360** [comment]
Hi @jonkemp, I really look forward to a new version of `inline-css` and `remote-content` without `vm2`. :wink: 
I guess just having a `remote-content@3.0.2` would be enough.

**Comment by jonkemp** [comment]
Updates to href-content and remote-content are available on npm.

**Comment by LucVidal360** [comment]
@jonkemp Thank you so much :pray:
