### ISSUE TITLE
For extract-css, do not use the obsolete batch package anymore

### ISSUE THREAD

**Issue by binarykitchen** [jonkemp/inline-css#131]
**Problem**

`extract-css` relies on a broken npm package named `batch`, see
https://github.com/jonkemp/inline-css/blob/master/packages/extract-css/package.json#L17

The npm package `batch` has issues, is broken, and isn't maintained for 7 years:
https://github.com/visionmedia/batch/blob/master/index.js

The cause is, it requires the `emitter` package which isn't listed under dependencies and breaks modern TS builds.

A possible solution would be to replace batch with another package with similar functionality.

**Comment by jonkemp** [comment]
Fixed in 951529a
