### ISSUE TITLE
Feature Idea: Remove class attributes

### ISSUE THREAD

**Issue by danieldiekmeier** [jonkemp/inline-css#21]
I'm using [gulp-inline-css](https://www.npmjs.com/package/gulp-inline-css) in a project, but I additionally have to use [gulp-attr-remover](https://github.com/othree/gulp-attr-remover) to remove the classes, because I don't need them anymore after the CSS is inlined.

Maybe this could be added to the inline-css core?

**Comment by jonkemp** [comment]
Well this is embarrassing. This feature was already added via a pull request, but it is not documented. Check out the commit here to see the code, tests and how to pass the option.

3faf40f

So I guess this issue needs to be changed to add the documentation for this feature and to gulp-inline-css as well. Thanks for bringing this to my attention!

**Comment by jonkemp** [comment]
Documentation has now been added. Thanks again.

**Comment by danieldiekmeier** [comment]
Thanks, awesome!
