### ISSUE TITLE
Add ignore attribute to a style block for styles not desired to be inlined

### ISSUE THREAD

**Issue by cjcheshire** [jonkemp/inline-css#22]
How about an option to allow a style tag in the head to be preserved and not inlined throughout the document?  Perhaps a data attribute on the tag?

```
<style data-prevent-inline="true">
…
</style>

**Comment by jonkemp** [comment]
What's the use case?

**Comment by cjcheshire** [comment]
I was looking at an email boiler template and found some styles are suggested to not be inlined.  

I guess it goes against your plugin though (which is awesome btw).

**Comment by jonkemp** [comment]
I believe you can accomplish that with this option.

https://github.com/jonkemp/inline-css#optionsapplystyletags

Although, looking at the test cases, I don't see a test for it. So it is missing coverage there.

Can you try that and let me know if that works? I'll try to find time to add the missing tests.

**Comment by cjcheshire** [comment]
Ah yes, that does work!

Thanks @jonkemp.
