### ISSUE TITLE
Options url is required. 

### ISSUE THREAD

**Issue by martinlanglois** [jonkemp/inline-css#24]
Not sure if this qualifies as an issue & perhaps I am simply missing ou on something but . 

the example does not work for me. 

```var inlineCss = require('inline-css');
    var html = "<style>div{color:red;}</style><div/>";
inlineCss(html,options)
        .then(function(html) { console.log(html); }); ```
will simply throw an error : 
options.url is required... 
providing an empty string on options.url
will result in the same thing. 

my script only inline <style><style> ... no <link> tag. 
not sure what I am supposed to provide in the options.url property... :S 

UPDATE : 
just noticed that if you pass a random string. 
the module works as expected... 
just not sure what options.url actually does in that case... not seeing any files being created..

**Comment by jonkemp** [comment]
This is noted in the docs.

https://github.com/jonkemp/inline-css#optionsurl

**Comment by trullock** [comment]
It would be helpful if the example under `usage` in the readme showed the required "options". Also the description for what to provide to `options.url` isn't fantastic, how does it work, does it get prepended or does it work like base-href?

**Comment by olsonpm** [comment]
also this doesn't throw an error with a stacktrace.  Looks like you guys throw a string which prevents us from knowing where this error came from
