### ISSUE TITLE
url path in options

### ISSUE THREAD

**Issue by XOP** [jonkemp/inline-css#28]
Stucked with an issue trying to provide relative path to `url` option.
Later realized it actually requires absolute path, with the `protocol` specified.

Checked the tests in repo and got the setup from there,
It only worked with the following:
```js
inlineCss(html, {
    url: 'file://' + htmlFolder + '/'
})
```

this is inconvenient for the config,
it's seems that the option with requiring and feeding CSS file is more attractive.
(`extraCss: cssContents`)

Could you explain why it is like that
and are there ways to improve that?

**Comment by jonkemp** [comment]
It's like that because it reads the html and looks for stylesheet references. It has to know if they are local files or external to get the contents of the stylesheet.
