### ISSUE TITLE
Preserving embedded css or not inlining select css

### ISSUE THREAD

**Issue by jchinchilla** [jonkemp/inline-css#3]
I use the inline-css - works very well. 
I also use PreserverMediaQueries - works very well too!
Wondering if I could request an add-on to somehow preserve or not remove any embedded css or css within some "Not inline" comment. Thanks! Loving this!

**Comment by jonkemp** [comment]
I believe you can do this by setting the options `removestyletags` and `removelinktags` to `false`.

https://github.com/jonkemp/inline-css#optionsremovestyletags
https://github.com/jonkemp/inline-css#optionsremovelinktags
