### ISSUE TITLE
Inline Conversion

### ISSUE THREAD

**Issue by Ankiewicz** [jonkemp/inline-css#35]
Up inlining - your inliner is turning all of my '&" into the html element '&amp;' So now any url's and non breaking spaces are now `'&amp;amp;nbsp;`'

**Comment by jonkemp** [comment]
Closing because it is a duplicate of #34. However, I will state this again here. This is a repo for an node.js module, not a support site for Zurb's Responsive Email Inliner tool. I don't work for Zurb or support their code, so please file an issue with them.

**Comment by Ankiewicz** [comment]
Their inline page links to your repo...
