### ISSUE TITLE
Handling of '=' (equals) symbol outside of HTML attributes

### ISSUE THREAD

**Issue by ClementParis016** [jonkemp/inline-css#39]
Hey there,

So, the following code:
```js
var inlineCss = require('inline-css');
var html = "<style>h2{color:red;}</style><h2><%= raw_slide_data slide, :title %></h2>";

inlineCss(html, {applyStyleTags: false, url: 'https://google.com'})
    .then(function(html) { console.log(html); });
```

Returns:
```html
<h2><%= raw_slide_data="" slide,="" :title="" %=""></%=></h2>
```

I guess the equals symbol in the opening ERB delimiter (<%=) is what makes inliner add others equals and double quotes. Should we consider this as an issue? Or maybe there is a way I could work around this?

For the story, I'm working on building emails with [Foundation for Emails](https://github.com/zurb/foundation-emails/) (this tells you from how far I'm coming down the road to solving my problem) to use within a Rails project (that's why I have ERB variables in my HTML).

**Comment by jonkemp** [comment]
It only supports HTML as far as I'm aware. So templating code is not supported at this time.

**Comment by ClementParis016** [comment]
Ok, thanks, I will take a closer look at the source to see if I can tweak this to suit my own use case.

**Comment by marvinhuebner** [comment]
@ClementParis016 did you found a solution for this? I have also some trouble with templating code and the inliner (through foundation for emails)

https://github.com/zurb/foundation-emails/issues/656

**Comment by ClementParis016** [comment]
@marvinhuebner indeed I did found a solution. The inliner was escaping special characters so I had to encode it first, then run the inliner and then decode the output. I can't remember exactly how I did it, but I can get back to the project later and come back to you if you want to know the details ;)
