### ISSUE TITLE
Greater Than and Less than Signs getting converted to &lt; &gt;

### ISSUE THREAD

**Issue by coreyschaaf** [jonkemp/inline-css#41]
**How can we reproduce this bug?**
If you include the following markup in order for my email sender to inject a dynamic coupon code into individual emails.

`<<LCG Program\TG LCG Coupon Code Default='246996'>>`

After the code above is run through the inliner, the result is below. 
`&lt;<lcg program\tg="" lcg="" coupon="" code="" default="246996">&gt;</lcg>`

**What happened instead?**
The code shouldn't have broken. My expectation was that it would be as I entered it. 
`<<LCG Program\TG LCG Coupon Code Default='246996'>>`

I also reference this bug in the foundation forum here: 
[http://foundation.zurb.com/forum/posts/39801-question-about-characters-changing-after-using-in-liner-using-sass-version-of-foundation-for-emails](url)

**Comment by coreyschaaf** [comment]
Any movement on this?

**Comment by jonkemp** [comment]
No. I added some labels. Anyone can contribute.

**Comment by daveycakes** [comment]
Hey @coreyschaaf I may have a solution for you, but need help with verifying this before I issue a pull request.

Would have time to try a branch I made on my fork?

npm install https://github.com/daveycakes/inline-css.git#interpol 

This gives a new option, **protect**
This property accepts an array of strings, and each string you include will be kept out out of the inlining process with replace calls, and then added back in after the inlining has completed.

eg: `inlineCss(data,{url: url, protect: ['{{','}}']}).then( ... )`

in your case, `protect: ['<<', '>>']` should work, based on tests I've run. It would be great to see if this works for you.

I want to make sure it works well before I clean it up a little and provide documentation.

**Comment by jonkemp** [comment]
The latest update can safely ignore those blocks now.

https://github.com/jonkemp/gulp-inline-css#optionscodeblocks

**Comment by coreyschaaf** [comment]
@jonkemp the issue I described above ... still happens even after I update. 
below is an example that throws an error during inlining

<h2 class="text-center"><b>Subtotal: $<<ShopperInfo\Total>></b></h2>

**Comment by jonkemp** [comment]
@coreyschaaf Please post a sample gulpfile or a link to a repo where sample (or actual) code can be inspected. Thanks.

**Comment by coreyschaaf** [comment]
@jonkemp 
`import gulp     from 'gulp';
import plugins  from 'gulp-load-plugins';
import browser  from 'browser-sync';
import rimraf   from 'rimraf';
import panini   from 'panini';
import yargs    from 'yargs';
import lazypipe from 'lazypipe';
import inky     from 'inky';
import fs       from 'fs';
import siphon   from 'siphon-media-query';
import path     from 'path';
import merge    from 'merge-stream';
import beep     from 'beepbeep';
import colors   from 'colors';
//added this to include gulp-chmod
import chmod    from 'gulp-chmod';
//added this file to add archive funtionality
import ignore   from 'gulp-ignore';
import yfm      from 'yaml-front-matter';


const $ = plugins();

// Look for the --production flag
const PRODUCTION = !!(yargs.argv.production);

// Declar var so that both AWS and Litmus task can use it.
var CONFIG,
  exec = require('child_process').exec;
 

// Build the "dist" folder by running all of the above tasks
gulp.task('build',
  gulp.series(clean, pages, sass, images, inline));

// Build emails, run the server, and watch for file changes
gulp.task('default',
  gulp.series('build', server, watch));

// Build emails, then send to litmus
gulp.task('litmus',
  gulp.series('build', creds, aws, litmus));

// Build emails, then zip
gulp.task('zip',
  gulp.series('build', zip));

// Delete the "dist" folder
// This happens every time a build starts
function clean(done) {
  rimraf('dist', done);
}

// Compile layouts, pages, and partials into flat HTML files
// Then parse using Inky templates
function pages() {
  return gulp.src(['src/pages/**/*.html', '!src/pages/archive/**/*.html'])
    .pipe(panini({
      root: 'src/pages',
      layouts: 'src/layouts',
      partials: 'src/partials',
      helpers: 'src/helpers',
      data: 'src/data'
    }))
    .pipe(inky())
    .pipe(chmod(755)) //added this to fix file perms
    .pipe(gulp.dest('dist'));
}

// Reset Panini's cache of layouts and partials
function resetPages(done) {
  panini.refresh();
  done();
}

// Compile Sass into CSS
function sass() {
  return gulp.src('src/assets/scss/app.scss')
    .pipe($.if(!PRODUCTION, $.sourcemaps.init()))
    .pipe($.sass({
      includePaths: ['node_modules/foundation-emails/scss']
    }).on('error', $.sass.logError))
    .pipe($.if(PRODUCTION, $.uncss(
      {
        html: ['dist/**/*.html']
      })))
    .pipe($.if(!PRODUCTION, $.sourcemaps.write()))
    .pipe(gulp.dest('dist/css'));
}

// Copy and compress images
function images() {
  return gulp.src(['src/assets/img/**/*', '!src/assets/img/archive/**/*'])
    .pipe($.imagemin())
    .pipe(gulp.dest('./dist/assets/img'));
}

// Inline CSS and minify HTML
function inline() {
  return gulp.src('dist/**/*.html')
    .pipe($.if(PRODUCTION, inliner('dist/css/app.css')))
    .pipe(gulp.dest('dist'));
}

// Start a server with LiveReload to preview the site in
function server(done) {
  browser.init({
    server: 'dist'
  });
  done();
}

// Watch for file changes
function watch() {
  gulp.watch('src/pages/**/*.html').on('change', gulp.series(pages, inline, browser.reload));
  gulp.watch(['src/layouts/**/*', 'src/partials/**/*']).on('change', gulp.series(resetPages, pages, inline, browser.reload));
  gulp.watch(['../scss/**/*.scss', 'src/assets/scss/**/*.scss']).on('change', gulp.series(resetPages, sass, pages, inline, browser.reload));
  gulp.watch('src/assets/img/**/*').on('change', gulp.series(images, browser.reload));
}

// Inlines CSS into HTML, adds media query CSS into the <style> tag of the email, and compresses the HTML
function inliner(css) {
  var css = fs.readFileSync(css).toString();
  var mqCss = siphon(css);

  var pipe = lazypipe()
    .pipe($.inlineCss, {
      applyStyleTags: false,
      removeStyleTags: true,
      preserveMediaQueries: true,
      removeLinkTags: true
    })
    .pipe($.replace, '', `<style>${mqCss}</style>`)
    .pipe($.htmlmin, {
      collapseWhitespace: true,
      minifyCSS: true
    });

  return pipe();
}

// Ensure creds for Litmus are at least there.
function creds(done) {
  var configPath = './config.json';
  try { CONFIG = JSON.parse(fs.readFileSync(configPath)); }
  catch(e) {
    beep();
    console.log('[AWS]'.bold.red + ' Sorry, there was an issue locating your config.json. Please see README.md');
    process.exit();
  }
  done();
}

// Post images to AWS S3 so they are accessible to Litmus test
function aws() {
  var publisher = !!CONFIG.aws ? $.awspublish.create(CONFIG.aws) : $.awspublish.create();
  var headers = {
    'Cache-Control': 'max-age=315360000, no-transform, public'
  };

  return gulp.src('./dist/assets/img/*')
    // publisher will add Content-Length, Content-Type and headers specified above
    // If not specified it will set x-amz-acl to public-read by default
    .pipe(publisher.publish(headers))

    // create a cache file to speed up consecutive uploads
    //.pipe(publisher.cache())

    // print upload updates to console
    .pipe($.awspublish.reporter());
}

// Send email to Litmus for testing. If no AWS creds then do not replace img urls.
function litmus() {
  var awsURL = !!CONFIG && !!CONFIG.aws && !!CONFIG.aws.url ? CONFIG.aws.url : false;

  return gulp.src('dist/**/*.html')
    .pipe($.if(!!awsURL, $.replace(/=('|")(\/?assets\/img)/g, "=$1"+ awsURL)))
    .pipe($.litmus(CONFIG.litmus))
    .pipe(gulp.dest('dist'));
}

// Copy and compress into Zip
function zip() {
  var dist = 'dist';
  var ext = '.html';

  function getHtmlFiles(dir) {
    return fs.readdirSync(dir)
      .filter(function(file) {
        var fileExt = path.join(dir, file);
        var isHtml = path.extname(fileExt) == ext;
        return fs.statSync(fileExt).isFile() && isHtml;
      });
  }

  var htmlFiles = getHtmlFiles(dist);

  var moveTasks = htmlFiles.map(function(file){
    var sourcePath = path.join(dist, file);
    var fileName = path.basename(sourcePath, ext);

    var moveHTML = gulp.src(sourcePath)
      .pipe($.rename(function (path) {
        path.dirname = fileName;
        return path;
      }));

    var moveImages = gulp.src(sourcePath)
      .pipe($.htmlSrc({ selector: 'img'}))
      .pipe($.rename(function (path) {
        path.dirname = fileName + '/assets/img';
        return path;
      }));

    return merge(moveHTML, moveImages)
      .pipe($.zip(fileName+ '.zip'))
      .pipe(gulp.dest('dist'));
  });

  return merge(moveTasks);
}


`

**Comment by coreyschaaf** [comment]
@jonkemp here is some html that I am attempting to inline (note I'm using Foundation For Emails full stack)

`
  
  <row class="sca-hero-image-container">
    <columns small="12" large="12" >
      <center>
        <a href="{{ variables.root-portal }}/shopping-cart/?activecartid=<<ShopperInfo\CartLink>>&trk_module=sca">
          <img src="{{ variables.root-image }}/automated-email/sca/tg-sca-1-hero.jpg" alt="You left some items in your cart.">
        </a>
      </center>
    </columns>
  </row>
  

  
  <row>
    <columns small="12" large="12">
      <wrapper  class="sca-main-content-block">
        <h3 class="text-center">Why wait? Stock is limited.</h3>
        <br>
        <center>
          <button href="{{ variables.root-portal }}/shopping-cart/?activecartid=<<ShopperInfo\CartLink>>&trk_module=sca" class="small">Complete Your Purchase</button>
        </center>
      </wrapper>
    </columns>
  </row>
  
  
  
  <row>
    <columns small="12" large="12">
      <row class="collapse">
        <columns>
            
            <<ShopperInfo\CartItemHtml>>
            
        </columns>
      </row>
      <row class="collapse">
        <columns>
          <row>
            <columns small="12" large="12" class="sca-product-total">
              <h2 class="text-center"><b>Subtotal: $<<ShopperInfo\Total>></b></h2>
              <center>
                <button href="{{ variables.root-portal }}/shopping-cart/?activecartid=<<ShopperInfo\CartLink>>&trk_module=sca" class="small cart-button"><b>View Cart</b></button>
              </center>
            </columns>
          </row>
        </columns>
      </row>
    </columns>
  </row>
  

  
  <row class="sca-social-proof-container">
    <columns small="12" large="12" >
      <center>
        <a href="{{ variables.root-portal }}/shopping-cart/?activecartid=<<ShopperInfo\CartLink>>&trk_module=sca">
          <img src="{{ variables.root-image }}/automated-email/shared/tg-social-proof-1.jpg" alt="Customer For Life">
        </a>
      </center>
    </columns>
  </row>
  
  {{> footer-navigation }}
  {{> footer-copyright }}
`

**Comment by jonkemp** [comment]
```javascript
// Inlines CSS into HTML, adds media query CSS into the <style> tag of the email, and compresses the HTML
function inliner(css) {
  var css = fs.readFileSync(css).toString();
  var mqCss = siphon(css);

  var pipe = lazypipe()
    .pipe($.inlineCss, {
      applyStyleTags: false,
      removeStyleTags: true,
      preserveMediaQueries: true,
      removeLinkTags: true,
      codeBlocks: { myBlocks: { start: '<<', end: '>>' } }
    })
    .pipe($.replace, '<!-- <style> -->', `<style>${mqCss}</style>`)
    .pipe($.htmlmin, {
      collapseWhitespace: true,
      minifyCSS: true
    });

  return pipe();
}
```

You need to add the new codeBlocks option. I've updated your inline function above. Let me know if that doesn't work.

**Comment by coreyschaaf** [comment]
@jonkemp 
![error](https://user-images.githubusercontent.com/6249547/37678611-8cef7880-2c4c-11e8-823c-23998a20ffe4.jpg)

**Comment by coreyschaaf** [comment]
In order to get around this, what I've done in the past is comment out the html that causes the problem 

The inliner handles this fine:
<

But chokes on this:
Subtotal: $<<ShopperInfo\Total>>

**Comment by jonkemp** [comment]
@coreyschaaf that error is not from this module, it's from foundation-cli. Can you post your package.json file?

**Comment by jonkemp** [comment]
@coreyschaaf make sure you have gulp-inline-css v3.2.0 installed.
