### ISSUE TITLE
Outlook web client Margin support

### ISSUE THREAD

**Issue by davidhouweling** [jonkemp/inline-css#43]
foundation-emails have been using capital M margin as well as lowercase M margin. The reason for this is that by standards it should be lower case, however Outlook web client requires it to be upper case.

I created a "technical solution" in https://github.com/zurb/foundation-emails/issues/443, which they suggested I ask to incorporate it into the inliner.

If you agree, I can create a PR for do it, but i was thinking it should probably be encapsulated in a flag such as 'emailAttributes' or so, so that for normal use cases we don't inject Margin everywhere.

**Comment by jonkemp** [comment]
I would be interesting in seeing the pull request. And yes I think it should be behind and option.

**Comment by dudeonthehorse** [comment]
Сapital Мargin is a hack for Outlook.com webmail. 

But now Outlook.com => Live.com

Hack no need more.
