### ISSUE TITLE
options.url needs more documentation

### ISSUE THREAD

**Issue by GriffinSauce** [jonkemp/inline-css#51]
The documentation on this option is very meager. There are two earlier issues describing misunderstanding the option. It would be great to make this easier to jump in.

Am I right to interpret that this is an absolute path that is prepended to any relative paths in the CSS? If that's true it's probably good to add that to the docs. (and if not: the actual truth ;) )

Since it's required; Adding it to the examples instead of an `options` placeholder is probably also a good idea. That makes the example ready to go.

Cheers!

**Comment by maikeldaloo** [comment]
+1
No idea what to do right now.

**Comment by jonkemp** [comment]
@GriffinSauce I agree.

@maikeldaloo I'm not sure how to help you.

**Comment by jonkemp** [comment]
@GriffinSauce `options.url` is the path to your html file, e.g. `file://path/to/html`.

**Comment by computersarecool** [comment]
+1
I agree, for example, in your example, you do not list any options. I am getting an error `ENOTFOUND` for the options.url when I leave it as default.  In my html, it is just the name of a file in the same directory, so I am not sure why this is wrong.

**Comment by GriffinSauce** [comment]
@jonkemp that should be in the readme.

**Comment by daveycakes** [comment]
I've done a little work on this, as per [this pull request](https://github.com/jonkemp/inline-css/pull/63)

**Comment by jonkemp** [comment]
@daveycakes would you be willing to update the documentation here as well?

https://github.com/jonkemp/gulp-inline-css

It's a gulp plugin that just uses this module.

**Comment by daveycakes** [comment]
@jonkemp yeah, why not.
Heh, that might have saved me from doing my own script for gulp, but it was pretty easy to work with.
