### ISSUE TITLE
Feature request: exclude some styles from inlining/removal

### ISSUE THREAD

**Issue by slavafomin** [jonkemp/inline-css#56]
Hello!

Thank you for this great library!

But, is it possible to exclude some CSS styles from inlining/removal? I want only a subset of styles to be inlined.

Consider this example:

```html
<style>
p {
  font-size: 12px;
}
</style>

<style data-no-inline>
a {
  color: red;
}
</style>
```

I want first styles to be inlined, but second styles skipped and leaved as is.

Thanks!

**Comment by jonkemp** [comment]
Fixed 7fa2f470f0f0fa55849228aa374ce3cb9b8b2c70. There is a new option for this in v2.4.0.
