### ISSUE TITLE
When there's interpolated variables, the templates break

### ISSUE THREAD

**Issue by yasuf** [jonkemp/inline-css#60]
Hey, we're a SF company and we use your library, we're pretty happy with it keep up the good work! 

There's something we noticed:
When there's an interpolated variable like `<p class="paragraph" style="background: {{color}]>hello</p>`, the styles from the class won't be part of the style attribute, and also this breaks the inline styles of other `<p>` tags in the same template, they don't get the styles either.

**Comment by richardsengers** [comment]
It's something I would like to know as well. Can we make use of interpolation?

**Comment by jonkemp** [comment]
I'm afraid I don't understand the question.

**Comment by carlosyasu91** [comment]
when you have a `<p style="background: {{ color}}, font-size: 20px"> </p>`, all of the other `p` tags will not get inline styles, I've tested this many times and this is what consistently happens

**Comment by jonkemp** [comment]
Maybe this is a typo, but in `<p style="background:{{color}}, font-size: 20px"> </p>` the comma should be a semicolon, right?

Anyways, the fact that this currently doesn't work means it would be a feature request rather than a bug report. Do you agree?

**Comment by carlosyasu91** [comment]
I agree, this is probably a feature request

**Comment by richardsengers** [comment]
Agree on that! It is a feature request which would be awesome :-)

**Comment by daveycakes** [comment]
Hello @yasuf would you be able to provide two small samples of html, one for input, one for desired output?

I'm toying with this problem at the moment and it would help me test.

**Comment by daveycakes** [comment]
I have started work on a feature, but need help to make sure that the thing will work.
There is a branch on my fork, which you can test if you install it:
npm install https://github.com/daveycakes/inline-css.git#interpol 

This gives a new option, **protect**
This property accepts an array of strings, and each string you include will be kept out out of the inlining process with replace calls, and then added back in after the inlining has completed.

eg: `inliner(data,{url: url, protect: ['{{','}}']}).then( ... )`

I want to make sure it works well before I clean it up a little and provide documentation.

**Comment by daveycakes** [comment]
Having spent  a little time on this, I think it would be better addressed in another project by @jonkemp , https://github.com/jonkemp/extract-css

I have a solution working in my branch which proves how it could be done, but the code is kind of shoehorned in, in a way which upsets the structure and reduces the maintainability of inline-css.

A new option could then be passed in to inline-css, where it would make it to extract-css.

I hope to take a stab at this when I have a quite moment.

**Comment by fjaeger** [comment]
Is there any progress regarding this feature request? I have the very same problem and would love to see some solution to it :-)

**Comment by evanre** [comment]
Hi. +1 =) It would be great to get any update regarding this feature request. Thanks

**Comment by jonkemp** [comment]
There's been no movement on this. I am not working on it. I don't know how to solve it. I've not had any offers for help.

**Comment by evanre** [comment]
Hi @jonkemp, thanks for your reply. Did you check @daveycakes's [draft](https://github.com/daveycakes/inline-css/commit/87d11df7016cdb5bc148e659d823db6eb44a43d6)? That "interpol" directive looks good. Sorry I haven't such skills to help you with this feature.

**Comment by jonkemp** [comment]
I looked into it this weekend and found a solution for this. The solution works well, but the public API still needs work. I don't have it in a branch yet, but I will either release it tonight or have it in a branch if that is not possible.

**Comment by jonkemp** [comment]
New version is out with this feature 7cdc0dd7f6df9516f488d1858703bff79a6e7478.

Here's the updated docs on how to use it.

https://github.com/jonkemp/inline-css#optionscodeblocks

Closing.

**Comment by evanre** [comment]
Hello, @jonkemp. Thank you very much for this update. Thats a really cool feature 👍 . Is there any estimate when gulp-inline-css will be updated according to a new inline-css version?

**Comment by jonkemp** [comment]
@evanre yes, I hope to get it updated tonight. It would have been last night, but unfortunately, I ran into the bug that most everyone that uses the plugin is probably aware of now.

**Comment by jonkemp** [comment]
New version of the gulp plugin is available.

https://github.com/jonkemp/gulp-inline-css/releases/tag/v3.1.3
