### ISSUE TITLE
Preserve inline style

### ISSUE THREAD

**Issue by baspetersnl** [jonkemp/inline-css#70]
When a style attribute is already in the inline style tag, the style attribute from the stylesheet shouldn't be added. 

For example;

`<style>
.link{
	padding:0;
	color:blue;
}
</style>
<a href='#' class='link' style='padding-left: 10px;'>Foo</a>`

gets converted to;

`
<a href="#" class="link" style="padding:0; color:blue; padding-left: 10px;">Foo</a>
`

**Comment by jonkemp** [comment]
Try passing `options.applyStyleTags` set to false in the options. It's true by default.
