### ISSUE TITLE
Using cheerio 0.19.0 which imports all of lodash

### ISSUE THREAD

**Issue by doug-numetric** [jonkemp/inline-css#71]
If you could update to cheerio 0.22.0, the resulting bundle size would be a lot smaller because it cherry-picks only the lodash methods it needs.

**Comment by jonkemp** [comment]
Updating cheerio breaks the unit tests. I need to investigate that.

**Comment by jonkemp** [comment]
Fixed 7de9eb7ee64541e8af9bd093bceb7434d8f6685f.
