### ISSUE TITLE
add attributes

### ISSUE THREAD

**Issue by TrySound** [jonkemp/inline-css#8]
Like width
- [ ] width -> width (even with percents)
- [ ] height -> heght
- [ ] text-align -> align
- [ ] vertical-align -> valign

**Comment by jonkemp** [comment]
Sorry, I don't understand this request.

**Comment by TrySound** [comment]
For now you apply only width as an attribute and only with pixels. Clients work fine with percentage values in attributes.

**Comment by MadLittleMods** [comment]
:+1:

Also add `align="center"` when `margin: 0 auto;` is defined.

**Comment by danmindru** [comment]
:+1: 
Would be awesome. Percentages make a lot of sense.

**Comment by theoephraim** [comment]
I think this is what you all want: https://github.com/jonkemp/inline-css/pull/16

**Comment by theoephraim** [comment]
There may be an outstanding issue here for still setting height/width when they use % values.
This PR only affects how tables are treated. Also, @MadLittleMods' request was not handled as it's a bit more complex than how the others were treated.

**Comment by theoephraim** [comment]
maybe close this and make a new issue? Oh also, I forgot to update the readme!

**Comment by jonkemp** [comment]
@theoephraim can you update the documentation?
