### ISSUE TITLE
Possible to add styles from file

### ISSUE THREAD

**Issue by magnuspaaske** [jonkemp/inline-css#81]
I'm using this script to add inline styles to emails. Right now I render the email with a template that includes the same CSS that's used on the front page. Right now the script will fetch the CSS from the CDN when running on production, but I was thinking if there's a way to simply inject the CSS from the file system?

It's possible I may have overlooked this in the documentation – if not, I was thinking if it was something we should add? :)

**Comment by jonkemp** [comment]
Yeah I think you just need to update the path to the stylesheet in your html.

**Comment by magnuspaaske** [comment]
I figured out the solution – the file that gets processed simply doesn't have any styles in its head and I use the `extraCss` feature with my full CSS file.
