### ISSUE TITLE
doesnt compile

### ISSUE THREAD

**Issue by jayagupta7** [jonkemp/inline-css#83]
on installing, i try to start project, i get following compile errors: 

Failed to compile.

./node_modules/pac-resolver/dnsResolve.js
Module not found: Can't resolve 'dns' in '/Users/jayagupta/consumer-report-widget/node_modules/pac-resolver'

./node_modules/pac-resolver/isResolvable.js
Module not found: Can't resolve 'dns' in '/Users/jayagupta/consumer-report-widget/node_modules/pac-resolver'

./node_modules/pac-resolver/isInNet.js
Module not found: Can't resolve 'dns' in '/Users/jayagupta/consumer-report-widget/node_modules/pac-resolver'

./node_modules/socks-proxy-agent/index.js
Module not found: Can't resolve 'dns' in '/Users/jayagupta/consumer-report-widget/node_modules/socks-proxy-agent'

./node_modules/ftp/lib/connection.js
Module not found: Can't resolve 'fs' in '/Users/jayagupta/consumer-report-widget/node_modules/ftp/lib'

./node_modules/get-uri/file.js
Module not found: Can't resolve 'fs' in '/Users/jayagupta/consumer-report-widget/node_modules/get-uri'

./node_modules/href-content/index.js
Module not found: Can't resolve 'fs' in '/Users/jayagupta/consumer-report-widget/node_modules/href-content'

./node_modules/ftp/lib/connection.js
Module not found: Can't resolve 'net' in '/Users/jayagupta/consumer-report-widget/node_modules/ftp/lib'

./node_modules/http-proxy-agent/index.js
Module not found: Can't resolve 'net' in '/Users/jayagupta/consumer-report-widget/node_modules/http-proxy-agent'

./node_modules/https-proxy-agent/index.js
Module not found: Can't resolve 'net' in '/Users/jayagupta/consumer-report-widget/node_modules/https-proxy-agent'

./node_modules/pac-proxy-agent/index.js
Module not found: Can't resolve 'net' in '/Users/jayagupta/consumer-report-widget/node_modules/pac-proxy-agent'

./node_modules/pac-resolver/myIpAddress.js
Module not found: Can't resolve 'net' in '/Users/jayagupta/consumer-report-widget/node_modules/pac-resolver'

./node_modules/socks/build/client/socksclient.js
Module not found: Can't resolve 'net' in '/Users/jayagupta/consumer-report-widget/node_modules/socks/build/client'

./node_modules/ftp/lib/connection.js
Module not found: Can't resolve 'tls' in '/Users/jayagupta/consumer-report-widget/node_modules/ftp/lib'

./node_modules/http-proxy-agent/index.js
Module not found: Can't resolve 'tls' in '/Users/jayagupta/consumer-report-widget/node_modules/http-proxy-agent'

./node_modules/https-proxy-agent/index.js
Module not found: Can't resolve 'tls' in '/Users/jayagupta/consumer-report-widget/node_modules/https-proxy-agent'

./node_modules/pac-proxy-agent/index.js
Module not found: Can't resolve 'tls' in '/Users/jayagupta/consumer-report-widget/node_modules/pac-proxy-agent'

./node_modules/socks-proxy-agent/index.js
Module not found: Can't resolve 'tls' in '/Users/jayagupta/consumer-report-widget/node_modules/socks-proxy-agent'

**Comment by tmasrat** [comment]
I ran into the same issue. I tired installing the modules one by one from bottom to top but I got stuck on dns. It requires a really old version of node and I am not going to downgrade node because other features will break.

**Comment by jonkemp** [comment]
What requires a really old version of node?

**Comment by tmasrat** [comment]
oh sorry I should have been more specific. dns does

**Comment by jonkemp** [comment]
What uses dns?

**Comment by tmasrat** [comment]
pac-resolve (refer to the above errors). All I did was install it and import it. I didn't even try to use it but it's breaking when I try to compile the app

**Comment by jonkemp** [comment]
Please try the latest version, just published tonight.

https://github.com/jonkemp/inline-css/releases/tag/v2.4.2

**Comment by CXJoyce** [comment]
I use the latest version 2.5.0. After i write "import inlineCss from 'inline-css';", it still have these errors.

**Comment by maxdulieu** [comment]
Same problem here with 2.5.1 on angular 8

**Comment by maxdulieu** [comment]
Solved it by using `npm install --save inline-css` instead of the default npm `npm i inline-css`

**Comment by yellow1912** [comment]
Yup same problem here, 1 year later.

**Comment by yellow1912** [comment]
I spoke too soon, the issue was yarn, I switched to pnpm and it works great.

**Comment by Louis-Muzellec-ATS** [comment]
> I spoke too soon, the issue was yarn, I switched to pnpm and it works great.

Could you please elaborate what you did ? I'm using npm and I've encountered the same problem as above.
I'm using the 3.0.0 release. (it doesn't work with 2.6.3 either) on angular 9.

**Comment by Louis-Muzellec-ATS** [comment]
The problem seems to be that inline-css doesn't work on the browser. Works perfectly fine server side.

**Comment by wujekbogdan** [comment]
I'm having the same issue. Just installed the `3.0.0` release and it doesn't seem to work in a browser.
