### ISSUE TITLE
Depends on deprecated package "flatten"

### ISSUE THREAD

**Issue by PeasOfMind** [jonkemp/inline-css#84]
Currently this package installs the deprecated package "flatten":
```
warning inline-css > flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
```
### Proposed modification
Swap dependency on "flatten" with a newer, not deprecated dependency like https://www.npmjs.com/package/array-flatten

I'd be happy to update the code to use the newer package & submit as a pull request.

**Comment by jonkemp** [comment]
Sounds good to me.

**Comment by jonkemp** [comment]
Strange that I don't see it when I do `npm install`.

**Comment by PeasOfMind** [comment]
I get the warning when I use `yarn` but not when I use `npm`
