### ISSUE TITLE
Downgrade bluebird to prevent bug in Firefox

### ISSUE THREAD

**Issue by DanielRuf** [jonkemp/inline-css#90]
See https://github.com/petkaantonov/bluebird/issues/1623

We should pin dependencies in general. In this case 3.5.5.

**Comment by jonkemp** [comment]
We actually don't even need it now that Node has native support for Promises. I ran it without using Bluebird and all the tests pass.

**Comment by jonkemp** [comment]
I'll make a PR and you can test if you want.

**Comment by jonkemp** [comment]
The PR is open. You can test it by including it in your dependencies like this: `"inline-css": "jonkemp/inline-css#remove-bluebird"`.
